#range crea una lista imutable de numeros entreos en suscecion en lista arimentica  numero=range(5)
numero= range(5)
print(numero[4])
numero1= range(4 , 10)
print(numero1[3])
numero2=range(10, 100 , 8)
print(numero2[9])